### ISSUE TITLE
Error Unity 2020.1.17 operator ??=

### ISSUE THREAD

**Issue by devinterx** [Leopotam/ecslite-unity-ugui#1]
Library\PackageCache\com.leopotam.ecslite.unity.ugui@3ed4bb6265\Runtime\Actions\EcsUguiActionBase.cs(69,21): error CS1525: Invalid expression term '='

**Comment by Leopotam** [comment]
@devinterx from `README`:
> Tested on unity 2020.3 (dependent on it)

from `package.json`:
> "unity": "2020.3",

I suggest to upgrade unity version.

**Comment by Leopotam** [comment]
@devinterx is issue solved?
